// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcaronlawihhnsrbpbpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjYXJvbmxhd2loaG5zcmJwYnB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MjkxMjAsImV4cCI6MjA2NTMwNTEyMH0.D-VMd-p0WOBvVktfXjoFyRyLZk8lHBD3BZCqzhdem-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);